-- Migration: Add missing columns to articles table for Ghost CMS integration
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- Safe to run multiple times (uses IF NOT EXISTS / conditional adds).

-- 1. seo_metadata — stores SEO metadata generated by the metadata agent
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'articles' AND column_name = 'seo_metadata'
    ) THEN
        ALTER TABLE articles ADD COLUMN seo_metadata jsonb;
        RAISE NOTICE 'Added seo_metadata column';
    ELSE
        RAISE NOTICE 'seo_metadata column already exists';
    END IF;
END $$;

-- 2. hero_image_url — URL of the hero/feature image
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'articles' AND column_name = 'hero_image_url'
    ) THEN
        ALTER TABLE articles ADD COLUMN hero_image_url text;
        RAISE NOTICE 'Added hero_image_url column';
    ELSE
        RAISE NOTICE 'hero_image_url column already exists';
    END IF;
END $$;

-- 3. infographic_url — URL of the infographic image
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'articles' AND column_name = 'infographic_url'
    ) THEN
        ALTER TABLE articles ADD COLUMN infographic_url text;
        RAISE NOTICE 'Added infographic_url column';
    ELSE
        RAISE NOTICE 'infographic_url column already exists';
    END IF;
END $$;

-- 4. metadata — generic JSONB for gdrive_watch, manual_edits, etc.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'articles' AND column_name = 'metadata'
    ) THEN
        ALTER TABLE articles ADD COLUMN metadata jsonb DEFAULT '{}'::jsonb;
        RAISE NOTICE 'Added metadata column';
    ELSE
        RAISE NOTICE 'metadata column already exists';
    END IF;
END $$;

-- 5. Create an RPC function that can run DDL (for auto-migration from app code)
CREATE OR REPLACE FUNCTION execute_ddl(ddl text) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
AS $$
BEGIN
    EXECUTE ddl;
END;
$$;
